language: node_js
node_js:
  - 12
git:
  submodules: false
cache:
  directories:
    - node_modules
script:
  - npm install -g @vue/cli
  - npm install
  - npm run build
  - npm run test:unit
  - npm install -D codecov
  - npm run test:coverage
  - npm run serve &
  - npm run cy:run
after-success:
  - ./node_modules/.bin/codecov --token="db3dd35a-2859-4b4f-80ef-1f69e10aef41"
branches:
  only:
    - main
deploy:
  provider: surge
  project: ./dist
  domain: iaas-frontend.surge.sh
  cleanup: false
  on:
    branch: main
