language: node_js
node_js:
  - 12
git:
  submodules: false
script:
  - npm install -g @vue/cli
  - npm install
  - npm run build
  - npm run test:unit
on:
  branch: Test
deploy:
  provider: surge
  project: ./dist
  domain: iaas-frontend.surge.sh
  cleanup: false
